# Generated by Django 4.1.2 on 2023-03-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='show',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/profile_default.png', null=True, upload_to='profiles/<django.db.models.query_utils.DeferredAttribute object at 0x0000029E248473D0>'),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='show',
            field=models.CharField(max_length=1000),
        ),
    ]
