# Generated by Django 4.1.2 on 2023-03-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0001_initial'),
        ('users', '0002_profile_user_alter_favorites_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='users.favorites'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movies_playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies_playlists', to='playlists.movie_playlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/user.png', null=True, upload_to='profiles/<django.db.models.query_utils.DeferredAttribute object at 0x000002DE0A14B490>'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tvs_playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='tvs_playlists', to='playlists.tv_playlist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to='users.whishlist'),
        ),
    ]
